export const bankBca = [
  {
    id: 1,
    title: "ATM BCA",
    text: [
      "• Masukkan kartu ATM, lalu PIN",
      "• Pilih menu “Transaksi Lainnya” – ‘Transfer” – “Ke Rek BCA Virtual Account”",
      "• Masukkan nomor BCA Virtual Account: 70020+Order ID",
      "Contoh:",
      "No. Peserta: 12345678, maka ditulis 7002012345678",
      "• Layar ATM akan menampilkan konfirmasi, ikuti instruksi untuk menyelesaikan transaksi",
      "• Ambil dan simpanlah bukti transaksi tersebut",
    ],
  },
  {
    id: 2,
    title: "M-BCA",
    text: [
      "• Login dengan akun Mbanking Anda",
      "• Pilih menu “m-Transfer”, pilih “BCA Virtual Account”",
      "• Input Kode Virtual Account: 39107+20+NRP",
      "Contoh:",
      "No. Peserta: 2020015000, maka ditulis 391072020015000",
      "• NRP: 1872001, maka ditulis 39107201872001",
      "• Klik menu “Simpan Daftar Transfer” untuk menyimpan nomor pembayaran mahasiswa",
      "• Klik OK kemudian Kirim/Send",
      "• Input PIN BCA untuk mengotorisasi",
      "• Ikuti instruksi untuk menyelesailkan transaksi",
    ],
  },
  {
    id: 3,
    title: "BCA Klik",
    text: [
      "• Klik “Internet Banking” pada kolom Pilih Metode Pembayaran di laman Pembayaran, lalu pilih “BCA KlikPay“.",
      "• Setelah klik “Bayar Sekarang“, kamu akan diarahkan ke website BCA KlikPay. Silakan selesaikan pembayaran melalui BCA KlikPay dalam waktu 1 jam untuk menghindari pembatalan transaksi secara otomatis.",
      "• Periksa kembali detail transaksi kamu, pilih pembayaran KlikBCA atau BCA Kartu Kredit, bila semuanya telah sesuai klik “• Kirim“.",
      "• Periksa kembali detail transaksi kamu sekali lagi, bila semuanya telah sesuai klik KIRIM OTP (One Time Password)",
      "• Melalui SMS ke nomor handphone kamu, BCA KlikPay akan mengirimkan kode OTP (One Time Password) dan segera masukkan kode OTP (One Time Password) tersebut pada website BCA KlikPay.",
      "• Transaksi Berhasil.",
    ],
  },
  {
    id: 4,
    title: "Internet Banking",
    text: [
      "• Login ke KlikBCA Individual",
      "• Pilih Menu “Transfer”",
      "• Pilih Menu “Transfer ke BCA Virtual Account”",
      "• Input Kode Virtual Account: 39107+20+NRP",
      "• Pilih “Lanjutkan” untuk melanjutkan pembayaran",
      "• Masukkan Respon KeyBCA Apply 1",
      "• Ikuti instruksi untuk menyelesaikan transaksi",
    ],
  },
];

export const bankBni = [
  {
    id: 1,
    title: "ATM BNI",
    text: [
      "• Masukkan kartu ATM, lalu PIN",
      "• Pilih menu “Transaksi Lainnya” – ‘Transfer” – “Ke Rek BCA Virtual Account”",
      "• Masukkan nomor BCA Virtual Account: 70020+Order ID",
      "Contoh:",
      "No. Peserta: 12345678, maka ditulis 7002012345678",
      "• Layar ATM akan menampilkan konfirmasi, ikuti instruksi untuk menyelesaikan transaksi",
      "• Ambil dan simpanlah bukti transaksi tersebut",
    ],
  },
  {
    id: 2,
    title: "M-BNI",
    text: [
      "• Login dengan akun Mbanking Anda",
      "• Pilih menu “m-Transfer”, pilih “BCA Virtual Account”",
      "• Input Kode Virtual Account: 39107+20+NRP",
      "Contoh:",
      "No. Peserta: 2020015000, maka ditulis 391072020015000",
      "• NRP: 1872001, maka ditulis 39107201872001",
      "• Klik menu “Simpan Daftar Transfer” untuk menyimpan nomor pembayaran mahasiswa",
      "• Klik OK kemudian Kirim/Send",
      "• Input PIN BCA untuk mengotorisasi",
      "• Ikuti instruksi untuk menyelesailkan transaksi",
    ],
  },
  {
    id: 3,
    title: "BNI Klik",
    text: [
      "• Klik “Internet Banking” pada kolom Pilih Metode Pembayaran di laman Pembayaran, lalu pilih “BCA KlikPay“.",
      "• Setelah klik “Bayar Sekarang“, kamu akan diarahkan ke website BCA KlikPay. Silakan selesaikan pembayaran melalui BCA KlikPay dalam waktu 1 jam untuk menghindari pembatalan transaksi secara otomatis.",
      "• Periksa kembali detail transaksi kamu, pilih pembayaran KlikBCA atau BCA Kartu Kredit, bila semuanya telah sesuai klik “• Kirim“.",
      "• Periksa kembali detail transaksi kamu sekali lagi, bila semuanya telah sesuai klik KIRIM OTP (One Time Password)",
      "• Melalui SMS ke nomor handphone kamu, BCA KlikPay akan mengirimkan kode OTP (One Time Password) dan segera masukkan kode OTP (One Time Password) tersebut pada website BCA KlikPay.",
      "• Transaksi Berhasil.",
    ],
  },
  {
    id: 4,
    title: "Internet Banking",
    text: [
      "• Login ke KlikBCA Individual",
      "• Pilih Menu “Transfer”",
      "• Pilih Menu “Transfer ke BCA Virtual Account”",
      "• Input Kode Virtual Account: 39107+20+NRP",
      "• Pilih “Lanjutkan” untuk melanjutkan pembayaran",
      "• Masukkan Respon KeyBCA Apply 1",
      "• Ikuti instruksi untuk menyelesaikan transaksi",
    ],
  },
];

export const bankMandiri = [
  {
    id: 1,
    title: "ATM Mandiri",
    text: [
      "• Masukkan kartu ATM, lalu PIN",
      "• Pilih menu “Transaksi Lainnya” – ‘Transfer” – “Ke Rek BCA Virtual Account”",
      "• Masukkan nomor BCA Virtual Account: 70020+Order ID",
      "Contoh:",
      "No. Peserta: 12345678, maka ditulis 7002012345678",
      "• Layar ATM akan menampilkan konfirmasi, ikuti instruksi untuk menyelesaikan transaksi",
      "• Ambil dan simpanlah bukti transaksi tersebut",
    ],
  },
  {
    id: 2,
    title: "M-Mandiri",
    text: [
      "• Login dengan akun Mbanking Anda",
      "• Pilih menu “m-Transfer”, pilih “BCA Virtual Account”",
      "• Input Kode Virtual Account: 39107+20+NRP",
      "Contoh:",
      "No. Peserta: 2020015000, maka ditulis 391072020015000",
      "• NRP: 1872001, maka ditulis 39107201872001",
      "• Klik menu “Simpan Daftar Transfer” untuk menyimpan nomor pembayaran mahasiswa",
      "• Klik OK kemudian Kirim/Send",
      "• Input PIN BCA untuk mengotorisasi",
      "• Ikuti instruksi untuk menyelesailkan transaksi",
    ],
  },
  {
    id: 3,
    title: "Mandiri Klik",
    text: [
      "• Klik “Internet Banking” pada kolom Pilih Metode Pembayaran di laman Pembayaran, lalu pilih “BCA KlikPay“.",
      "• Setelah klik “Bayar Sekarang“, kamu akan diarahkan ke website BCA KlikPay. Silakan selesaikan pembayaran melalui BCA KlikPay dalam waktu 1 jam untuk menghindari pembatalan transaksi secara otomatis.",
      "• Periksa kembali detail transaksi kamu, pilih pembayaran KlikBCA atau BCA Kartu Kredit, bila semuanya telah sesuai klik “• Kirim“.",
      "• Periksa kembali detail transaksi kamu sekali lagi, bila semuanya telah sesuai klik KIRIM OTP (One Time Password)",
      "• Melalui SMS ke nomor handphone kamu, BCA KlikPay akan mengirimkan kode OTP (One Time Password) dan segera masukkan kode OTP (One Time Password) tersebut pada website BCA KlikPay.",
      "• Transaksi Berhasil.",
    ],
  },
  {
    id: 4,
    title: "Internet Banking",
    text: [
      "• Login ke KlikBCA Individual",
      "• Pilih Menu “Transfer”",
      "• Pilih Menu “Transfer ke BCA Virtual Account”",
      "• Input Kode Virtual Account: 39107+20+NRP",
      "• Pilih “Lanjutkan” untuk melanjutkan pembayaran",
      "• Masukkan Respon KeyBCA Apply 1",
      "• Ikuti instruksi untuk menyelesaikan transaksi",
    ],
  },
];
